### ISSUE TITLE
cable types

### ISSUE THREAD

**Issue by Cowh3ad** [jenschr/USB-C-Connectors#1]
just wanted to know if the Korean Hroparts Elec TYPE-C-31-M-17 works with standard type-c cables. or if you need a different cabletype?

**Comment by jenschr** [comment]
@Cowh3ad Type C is always Type C :)

They fit well with all the cables I have used them for. One thing to be aware of regarding Hroparts - they are not as solid as some other connectors. I use these in all my projects + products and I have one board that took some proper abuse. The cable got pulled hard with the board plugged in and after that, the connector felt too loose. Based on that, I suspect that the metal is a bit thinner than connectors from Amphenol and Molex as I've had similar mishaps with these that in that case it went well, or the connector ripped loose.

Another thing is that many PCBA houses are not able to source from LCSC. I don't understand why they don't as, LCSC has been my (chip shortage) savior several times the last year.
