### ISSUE TITLE
How to instaall these 3D Models?

### ISSUE THREAD

**Issue by PsySc0rpi0n** [jenschr/USB-C-Connectors#2]
Instructions could be added, for new users.
For instance, in my case, I don't know how to install from this repository. There are a bunch of folders and I have no idea which ones are needed, nor where to place them!

Could you please add a few lines on how to install?

Thanks
Psy

**Comment by PsySc0rpi0n** [comment]
Apparently this has no 3D Models.

**Comment by jenschr** [comment]
True :-D
